### ISSUE TITLE
Additional unit tests and validations

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/tern.rbmi#25]
From https://github.com/insightsengineering/coredev-tasks/issues/245

- Some functions e.g. `s_rbmi_lsmeans` do not have tests (test coverage is < 60%) 
- `summarize_rbmi` does not have argument validation (i.e. the docs say `.labels` should be named `character`)

**Comment by pawelru** [comment]
The acceptance criteria would be to reach 80% coverage so that it passess autovalidate requirements.

**Comment by shajoezhu** [comment]
also, remove line https://github.com/insightsengineering/tern.rbmi/blob/main/R/tabulate_rbmi.R#L188, don't seem it is doing anything

**Comment by shajoezhu** [comment]
also, remove line https://github.com/insightsengineering/tern.rbmi/blob/main/R/tabulate_rbmi.R#L188, don't seem it is doing anything
