### ISSUE TITLE
R CMD CHECK ERROR and NOTE

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/tern.rbmi#73]
https://github.com/r-universe/pharmaverse/actions/runs/10861236954

* R-4.5-win
  ```
  * checking DESCRIPTION meta-information ... NOTE
  License stub is invalid DCF.
  ```

* R-4.5-linux
  (note as above)

* R-4.4-win
  (note as above)

* R-4.4-mac
  ```
    ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-h_tidy_pool.R:27:3'): h_tidy_pool is produced correctly ──────
  `result` (`actual`) not identical to `expected` (`expected`).
  
  actual vs expected
                       lower_cl_est
    actual[1, ]   -2.57577141468279
  - actual[2, ]   -2.6453193050416 
  + expected[2, ] -2.64531930504159
  
  `actual$lower_cl_est`:   "-2.57577141468279" "-2.6453193050416" 
  `expected$lower_cl_est`: "-2.57577141468279" "-2.64531930504159"
  ── Failure ('test-tidypool.R:41:3'): tidy.pool is produced correctly ───────────
  `result` (`actual`) not identical to `expected` (`expected`).
  
  actual vs expected
                       lower_cl_est
    actual[1, ]   -2.57577141468279
  - actual[2, ]   -2.6453193050416 
  + expected[2, ] -2.64531930504159
    actual[3, ]   -5.52033399517686
    actual[4, ]   -4.15418494506937
    actual[5, ]   -7.77106696884431
  
      actual$lower_cl_est | expected$lower_cl_est    
  [1] "-2.57577141468279" | "-2.57577141468279"   [1]
  [2] "-2.6453193050416"  - "-2.64531930504159"   [2]
  [3] "-5.52033399517686" | "-5.52033399517686"   [3]
  [4] "-4.15418494506937" | "-4.15418494506937"   [4]
  [5] "-7.77106696884431" | "-7.77106696884431"   [5]
  
  [ FAIL 2 | WARN 0 | SKIP 1 | PASS 4 ]
  ```

* R-4.3-mac
  (test failed as above)

If this is a fixable note - please add this to the r-cmd-check notes blocklist in all of our repos

**Comment by pawelru** [comment]
Also RHub fails due to missing dependency:
```
* checking re-building of vignette outputs ... [3s/3s] ERROR
Error(s) in re-building vignettes:
  ...
--- re-building ‘tern-rbmi.Rmd’ using rmarkdown
Quitting from lines 156-164 [unnamed-chunk-7] (tern-rbmi.Rmd)
Error: processing vignette 'tern-rbmi.Rmd' failed with diagnostics:
In order to use `method_bayes()` the `rstan` package must be installed. This can be installed from CRAN by running:
      install.packages('rstan')
Please note that for `rstan` to work you need to ensure you have a valid C++ toolchain; for details please see:
https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#configuring-c-toolchain
--- failed re-building ‘tern-rbmi.Rmd’
SUMMARY: processing the following file failed:
  ‘tern-rbmi.Rmd’
Error: Vignette re-building failed.
```

We might consider using a different method if we want to avoid adding `rstan` to Suggests

**Comment by shajoezhu** [comment]
rhub should have been fixed by https://github.com/insightsengineering/tern.rbmi/pull/75

**Comment by pawelru** [comment]
A new error for `rhub`:
```
── R CMD build ─────────────────────────────────────────────────────────────────
* checking for file ‘.../DESCRIPTION’ ... OK
* preparing ‘tern.rbmi’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘tern-rbmi.Rmd’ using rmarkdown
Quitting from lines 156-164 [unnamed-chunk-7] (tern-rbmi.Rmd)
Error: processing vignette 'tern-rbmi.Rmd' failed with diagnostics:
Boost not found; call install.packages('BH')
--- failed re-building ‘tern-rbmi.Rmd’
SUMMARY: processing the following file failed:
  ‘tern-rbmi.Rmd’
Error: Vignette re-building failed.
Execution halted
Error in proc$get_built_file() : Build process failed
Calls: <Anonymous> ... build_package -> with_envvar -> force -> <Anonymous>
Execution halted
Error: Process completed with exit code 1.
```

**Comment by shajoezhu** [comment]
> Also RHub fails due to missing dependency:
> 
> ```
> * checking re-building of vignette outputs ... [3s/3s] ERROR
> Error(s) in re-building vignettes:
>   ...
> --- re-building ‘tern-rbmi.Rmd’ using rmarkdown
> Quitting from lines 156-164 [unnamed-chunk-7] (tern-rbmi.Rmd)
> Error: processing vignette 'tern-rbmi.Rmd' failed with diagnostics:
> In order to use `method_bayes()` the `rstan` package must be installed. This can be installed from CRAN by running:
>       install.packages('rstan')
> Please note that for `rstan` to work you need to ensure you have a valid C++ toolchain; for details please see:
> https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#configuring-c-toolchain
> --- failed re-building ‘tern-rbmi.Rmd’
> SUMMARY: processing the following file failed:
>   ‘tern-rbmi.Rmd’
> Error: Vignette re-building failed.
> ```
> 
> We might consider using a different method if we want to avoid adding `rstan` to Suggests

adding rstan to suggests has not resolved this. need another close look into this

**Comment by pawelru** [comment]
No. This looks better than before.

Before:
- https://github.com/insightsengineering/tern.rbmi/actions/runs/11648245250

Now:
- https://github.com/insightsengineering/tern.rbmi/actions/runs/11695831375

I see that some pipelines become green which is good. What left is `noSuggest` and `macos`. For the former you would have to add some logic in the vigniette code to make it _pass_ without suggested packages. We have discussed this somewhere but I cannot recall it, I am sorry. My first idea is to control `eval` parameter of the effected code chunk (and all dependent ones that follows!) based on package existance. Yet another one (more simpler but also probably more radical) is to do this for all (!) code chunks in the vigniette header.

**Comment by shajoezhu** [comment]
> No. This looks better than before.
> 
> Before:
> 
> * https://github.com/insightsengineering/tern.rbmi/actions/runs/11648245250
> 
> Now:
> 
> * https://github.com/insightsengineering/tern.rbmi/actions/runs/11695831375
> 
> I see that some pipelines become green which is good. What left is `noSuggest` and `macos`. For the former you would have to add some logic in the vigniette code to make it _pass_ without suggested packages. We have discussed this somewhere but I cannot recall it, I am sorry. My first idea is to control `eval` parameter of the effected code chunk (and all dependent ones that follows!) based on package existance. Yet another one (more simpler but also probably more radical) is to do this for all (!) code chunks in the vigniette header.

yes, I know what you talking about. I was going to do that, and then saw your comment. Cool. leave this with me, I will fix this :)

**Comment by shajoezhu** [comment]
macos issue i think will remain. @pawelru was wondering what your thoughts on this?

**Comment by pawelru** [comment]
Would it be possible to control the tolerance? These changes are relatively very small.
