### ISSUE TITLE
[Question]: CRAN release planned?

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/tern.rbmi#79]
### What is your question?

Hi @shajoezhu and team, have you planned a CRAN release of `tern.rbmi`? 😁 That could simplify and enhance adoption by others 😉 
Cheers, Daniel

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by shajoezhu** [comment]
now we will! haha, because no user asked before

**Comment by shajoezhu** [comment]
see #81

**Comment by danielinteractive** [comment]
Super thanks a lot @shajoezhu !
